### ISSUE TITLE
Dynamic page change

### ISSUE THREAD

**Issue by jimijohnson** [TheoXiong/vue-table-dynamic#1]
Hi, I got a question. When I want to highlight certain row through external means, like a simple textbox. The table won't switch to the page with highlighted row. (For example I am on the second page which contains records 11-20 and highlighting row 5, I will still be on page 2, whereas I'd like to be moved to page 1).  
Was looking through documentation and couldn't find any data concerning actual page, or be able to move to certain page through code. Is there such a possibility?

**Comment by TheoXiong** [comment]
I added `toPage` method in version `0.1.0`.
You can use this method to manually switch pages

```
<template>
  <div style="width: 600px">
    <vue-table-dynamic :params="params" ref="table"></vue-table-dynamic>
  </div>
</template>

<script>
import VueTableDynamic from 'vue-table-dynamic'

const random = () => {
  return parseInt(Date.now() + Math.random() * 10000000).toString(16).slice(-6)
}

export default {
  name: 'Demo',
  data() {
    return {
      params: {
        data: [
          ['Index', `Data1`, `Data2`, `Data3`]
        ],
        header: 'row',
        pagination: true
      }
    }
  },
  mounted () {
    for (let i = 0; i < 200; i++) {
      this.params.data.push([i+1, `${random()}`, `${random()}`, `${random()}`])
    }

    setTimeout(() => {
      this.$refs.table.toPage(2)
    }, 2000)
  }
  components: { VueTableDynamic }
}
</script>
```

**Comment by jimijohnson** [comment]
Thank you very much!

**Comment by vaibhavkumar049** [comment]
@jimijohnson  @TheoXiong any method to get page number on which user clicked? this could help in pagination. For example if user is on 3rd page we could fire api api?page=3 something like this
