### ISSUE TITLE
能固定列么？

### ISSUE THREAD

**Issue by nileblack** [TheoXiong/vue-table-dynamic#2]
能固定列么？

**Comment by TheoXiong** [comment]
目前不支持，以后可以增加这个特性。

**Comment by SissioG** [comment]
It's a great Work! :) only one thing.. could you add the possibility to change background color and font color of each row? thanks.

**Comment by stayacid** [comment]
Actually, it would be great to made table's styles unscoped. I need to have possibility to overwrite them.

**Comment by TheoXiong** [comment]
> 能固定列么？

已增加固定列特性，版本：`0.2.1`
Added the feature of fixed columns, in version `0.2.1`

![scroll](https://user-images.githubusercontent.com/42533484/76924836-8c284a80-6912-11ea-9d29-48788f729bd7.gif)

**Comment by TheoXiong** [comment]
> It's a great Work! :) only one thing.. could you add the possibility to change background color and font color of each row? thanks.

It's a good idea.  
I'm also ready to support customize styles and themes.

You can open a new issue about this
