### ISSUE TITLE
Nice Feature Enhancement

### ISSUE THREAD

**Issue by ronroyce22** [TheoXiong/vue-table-dynamic#22]
What you have is great!  Gives me 99% of what I need.  What I think is missing that would be very useful is to have a way to have the column data be HTML and the HTML for the column is rendered rather than treated as text.  My use is to have a column with a anchor (<a>) or button (<button>) tag that can be used to either edit, delete, or some other action upon click

**Comment by IlanVivanco** [comment]
@ronroyce22 you can already do that using [slots](https://github.com/TheoXiong/vue-table-dynamic#slot).

For example:
```js
data: {
  table: {
  header: 'row',
  data: [
    ['Field', 'Value', 'Price'],
    ['#1', '<h2>My title</h2>', 123],
    ['#2', '<h2>Another title</h2>', 43],
  ],
  }
},
```
```html
<vue-table-dynamic :params="table" v-on:row-click="test">
  <template v-slot:column-1="{ props }">
    <strong>{{props.cellData * 1000}}</strong>
  </template>
  <template v-slot:column-1="{ props }">
    <span v-html="props.cellData"></span>
  </template>
  <template v-slot:column-2="{ props }">
    <span>${{props.cellData * 1000}}.00</span>
  </template>
</vue-table-dynamic>
```

It will render something like this
![image](https://user-images.githubusercontent.com/9307840/107271093-835ccd80-6a2a-11eb-97c0-f18744716a65.png)

**Comment by TheoXiong** [comment]
You can customize table cells by slot.

Here is a simple example：
https://github.com/TheoXiong/vue-table-dynamic/blob/master/dev/src/views/DefaultStyle.vue
 
![image](https://user-images.githubusercontent.com/42533484/129571604-f7b13e54-2eed-434c-b84f-36721cefeec3.png)
