### ISSUE TITLE
is there a way to add id to row?

### ISSUE THREAD

**Issue by RobinTHOREL** [TheoXiong/vue-table-dynamic#24]
First issue ; 

How to get the id of an row without display this id on the table?

Like the table is dynamic with an array, I don't know how to get the id without display it. Maybe hide a column?

Thanks

**Comment by TheoXiong** [comment]
You can use slots to customize data.
Here is a example：
https://github.com/TheoXiong/vue-table-dynamic/blob/master/dev/src/views/CustomCell.vue
