### ISSUE TITLE
Question : LoadData in Vuex

### ISSUE THREAD

**Issue by nicolascastel** [TheoXiong/vue-table-dynamic#5]
Hi,

Thanks for your component. 

Have you an example to load Data from vuex State? 

Regards,

**Comment by TheoXiong** [comment]
Hi,
There is no such case.
Can you describe your case？

Load data by `this.$store.state.params` in vue component, then pass it to vue-table-dynamic ?

**Comment by nicolascastel** [comment]
Hi,

I'm just starting with vuex, I tried to use the store to load the data (which come from an API) but without success.

Thank you for confirming that this is possible. I will work on the subject and come back to you in case of problems

**Comment by nicolascastel** [comment]
It's Ok ! It's not a compent's problem but an misunderstanding of vuex.

Thanks for your job!
