### ISSUE TITLE
Can we custom sort function？

### ISSUE THREAD

**Issue by KarmAbyss** [TheoXiong/vue-table-dynamic#7]
trying to leave the NaN type data on the bottom no matter ascending or descending

**Comment by TheoXiong** [comment]
Added  in version 0.2.5

example:
```
sort: [0, { 
    column: 1, 
    ascending: (a, b) => { return parseInt(a) > parseInt(b) ? 1 : -1 }, 
    descending: (a, b) => { return parseInt(b) > parseInt(a) ? 1 : -1 } 
    }
  ]
```
If the item of sort is a number, default sort function will be used for the column.
You can use `ascending/descending` to customize the sorting function
