### ISSUE TITLE
manual search example

### ISSUE THREAD

**Issue by KhoiDinh** [TheoXiong/vue-table-dynamic#9]
Can you provide an example of how to do the manual search in a table for 1 column and only that column. For the default search, it will search for the value we enter in all the columns, not just a selected column.

**Comment by TheoXiong** [comment]
Hi!
Thanks for your attention.

`search` method support searching in the specified column with version `0.2.2`.
Such as, `this.$refs.table.search('sometxt', [0])`, it will be searching in the first column

For more detail, you can see readme.

**Comment by TheoXiong** [comment]
```
/**
 * @param {String} searchValue: the keyword for matching
 * @param {Array} included: match in specified columns
 * @param {Array} excluded: not match in specified columns, priority over `included`
 */
search (searchValue, included, excluded)
```
